name: "Send email after workflow"

on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2 # Updated to v3 for Node.js 20 compatibility

      - name: "Setup Python environment"
        uses: actions/setup-python@v2 # Updated to v4 for Node.js 20 compatibility
        with:
          python-version: '3.x'

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip

      - name: "Send mail by executing Python script"
        run: python script.py
        env:
          WORKFLOW_NAME: ${{ github.workflow }}
          REPO_NAME: ${{ github.repository }}
          WORKFLOW_RUN_ID: ${{ github.run_id }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
